spring.application.name=Ecomm

spring.datasource.url=jdbc:mysql://mysql-167848b8-ishansingh453-48ad.h.aivencloud.com:10870/defaultdb?sslMode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#spring.application.name=Ecomm
#
#spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce
#spring.datasource.username=root
#spring.datasource.password=Ish@n781
#
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#
## JPA
#spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true

